export const RECV_ERROR_AT_GET_ALL_EMPLOYEE = 'RECV_ERROR_AT_GET_ALL_EMPLOYEE';
export const REQ_DATA_AT_GET_ALL_EMPLOYEE = 'REQ_DATA_AT_GET_ALL_EMPLOYEE';
export const RECV_DATA_AT_GET_ALL_EMPLOYEE = 'RECV_DATA_AT_GET_ALL_EMPLOYEE';
export const RECV_ERROR_AT_GET_ALL_PROJECT = 'RECV_ERROR_AT_GET_ALL_PROJECT';
export const REQ_DATA_AT_GET_ALL_PROJECT = 'REQ_DATA_AT_GET_ALL_PROJECT';
export const RECV_DATA_AT_GET_ALL_PROJECT = 'RECV_DATA_AT_GET_ALL_PROJECT';